
version: "3.8"

services:

  sconesdb: 
    image: mysql
    container_name: mysqldbcontainer
    ports:
      - 3308:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: scones
      MYSQL_PASSWORD: scones
      MYSQL_DATABASE: scones

  backend:
    image: r.edu.codespring.ro/scones/scones-compose/scones-backend-release:1.1.0
    container_name: backendcontainer
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_USERNAME: scones
      SPRING_DATASOURCE_PASSWORD: scones
      SPRING_DATASOURCE_URL: jdbc:mysql://sconesdb:3306/scones
      MINIO_ENDPOINT: http://minio
      MINIO_PORT: 9000
      MINIO_SECURE: false
      MINIO_ACCESS-KEY: sconesuser
      MINIO_SECRET-KEY: sconespassword
    depends_on:
      - sconesdb

  minio:
    image: bitnami/minio:2024.5.27-debian-12-r0
    restart: unless-stopped
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-storage:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin-password

  frontend:
    image: r.edu.codespring.ro/scones/scones-compose/scones-frontend-release:1.0.0
    container_name: frontendcontainer
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_HOST=localhost
      - REACT_APP_BACKEND_PORT=8080
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  db-data:
    driver: local




    # image: backend-test-2

     # image: frontend-image